on: 
    issue_comment:
      types: [created, edited]   
  
jobs:
  check_pr_comments:
    runs-on: ubuntu-latest
    name: Check PR comments contain strings
    steps:
     - name: Check PR comments contain string
       id: String-comment-check
       uses: amine-arb-2019/js-action@v1.4
       with:
         github-token: '${{ secrets.GITHUB_TOKEN }}'
         string-list: '@graalvmbot, signed' 
       #uses: amine-arb-2019/test-action-2@v1.12
       #with:
 
            
          
          
  
